version: 2

sources:
  - name: prod
    database: chainwalkers
    schema: prod
    tables:
      - name: optimism_blocks
      - name: optimism_txs
  - name: crosschain
    database: crosschain
    schema: core
    tables:
      - name: address_labels
      - name: ez_hourly_prices
  - name: ethereum
    database: ethereum
    schema: core
    tables:
      - name: fact_hourly_token_prices
  - name: ethereum_silver
    database: ethereum
    schema: silver
    tables:
      - name: optimism_state_hashes
      - name: optimism_submission_hashes
  - name: silver_crosschain
    database: crosschain
    schema: silver
    tables:
      - name: asset_metadata_coin_gecko
      - name: asset_metadata_coin_market_cap
      - name: hourly_prices_coin_gecko
      - name: hourly_prices_coin_market_cap
      - name: apis_keys
      - name: token_prices_priority_hourly
      - name: asset_metadata_priority
  - name: streamline_crosschain
    database: streamline
    schema: crosschain
    tables: 
      - name: node_mapping
  - name: crosschain_public
    database: crosschain
    schema: bronze_public
    tables:
      - name: user_abis
  - name: bronze_streamline
    database: streamline
    schema: |
      {{ "OPTIMISM_DEV" if var("STREAMLINE_USE_DEV_FOR_EXTERNAL_TABLES", False) else "OPTIMISM" }}
    tables:
      - name: receipts
      - name: blocks
      - name: transactions
      - name: debug_traceBlockByNumber
      - name: decoded_logs
  
  