version: 2

sources:
  - name: prod
    database: chainwalkers
    schema: prod
    tables:
      - name: optimism_blocks
      - name: optimism_txs
  - name: crosschain
    database: crosschain
    schema: core
    tables:
      - name: address_labels
      - name: ez_hourly_prices
  - name: ethereum
    database: ethereum
    schema: core
    tables:
      - name: fact_hourly_token_prices
  - name: shared
    schema: silver
    tables:
      - name: prices_v2
      - name: market_asset_metadata
  - name: legacy_silver
    database: flipside_prod_db
    schema: silver
    tables:
      - name: hours
      - name: market_asset_metadata
      - name: prices_v2
  - name: optimism_pools
    database: optimism
    schema: bronze
    tables:
      - name: SUSHI_DIM_DEX_POOLS
  - name: prices
    database: FLIPSIDE_PROD_DB
    schema: SILVER
    tables:
      - name: prices_v2
  - name: ethereum_silver
    database: ethereum
    schema: silver
    tables:
      - name: optimism_state_hashes
      - name: optimism_submission_hashes
  - name: silver_crosschain
    database: crosschain
    schema: silver
    tables:
      - name: asset_metadata_coin_gecko
      - name: asset_metadata_coin_market_cap
      - name: hourly_prices_coin_gecko
      - name: hourly_prices_coin_market_cap
      - name: apis_keys
      - name: token_prices_priority_hourly
      - name: asset_metadata_priority
  - name: streamline_crosschain
    database: streamline
    schema: crosschain
    tables: 
      - name: node_mapping

  
  