version: 2

sources:
  - name: prod
    database: chainwalkers
    schema: prod
    tables:
      - name: optimism_blocks
      - name: optimism_txs
  - name: crosschain
    database: "{{ 'crosschain' if target.database == 'OPTIMISM' else 'crosschain_dev' }}"
    schema: core
    tables:
      - name: dim_labels
      - name: ez_hourly_token_prices
  - name: ethereum
    database: ethereum
    schema: core
    tables:
      - name: fact_hourly_token_prices
  - name: ethereum_silver
    database: ethereum
    schema: silver
    tables:
      - name: optimism_state_hashes
      - name: optimism_submission_hashes
  - name: silver_crosschain
    database: "{{ 'crosschain' if target.database == 'OPTIMISM' else 'crosschain_dev' }}"
    schema: silver
    tables:
      - name: token_prices_priority_hourly
      - name: token_prices_all_providers_hourly
      - name: asset_metadata_priority
      - name: asset_metadata_all_providers
      - name: near_address_encoded
      - name: labels_combined
  - name: crosschain_public
    database: crosschain
    schema: bronze_public
    tables:
      - name: user_abis
  - name: bronze_streamline
    database: streamline
    schema: |
      {{ "OPTIMISM_DEV" if var("STREAMLINE_USE_DEV_FOR_EXTERNAL_TABLES", False) else "OPTIMISM" }}
    tables:
      - name: receipts
      - name: blocks
      - name: transactions
      - name: debug_traceBlockByNumber
      - name: decoded_logs
      - name: confirm_blocks
  - name: optimism_silver
    database: optimism
    schema: silver
    tables:
      - name: verified_abis
      - name: overflowed_traces
      - name: overflowed_traces_v2
  - name: optimism_bronze_api
    database: optimism
    schema: bronze_api
    tables:
      - name: contract_abis
  - name: github_actions
    database: optimism
    schema: github_actions
    tables:
      - name: workflows
  - name: external_gold_defillama
    database: external
    schema: defillama
    tables:
      - name: dim_chains
